packages:
  - 'wp-content/plugins/lohko'
  - 'wp-content/plugins/jcore-portti'
  - 'wp-content/themes/ilme'

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  esbuild: true

publicHoistPattern:
  - 'prettier'
